FilmBilgileriSistemi/Areas/Admin/Controllers/SliderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FilmBilgileriSistemi.Areas.Admin.Controllers
{
    public class SliderController : Controller
    {
        FilmBilgileriEntities DB = new FilmBilgileriEntities();
       
        // GET: Admin/Slider
        public ActionResult Index()
        {
           var model= DB.Slider_Table.OrderByDescending( x => x.ID).ToList();
            return View(model);
        }
        public ActionResult Add()
        {
            return View();
        }
        public ActionResult AddSlider(Slider_Table model)
        {
            if(ModelState.IsValid)
            {
                DB.Slider_Table.Add(model);
                DB.SaveChanges();
            }
            return RedirectToAction("Index");
            return View();
        }
    }
}

FilmBilgileriSistemi/Areas/Admin/Views/Slider/Add.cshtml
@model FilmBilgileriSistemi.Slider_Table

@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row-fluid sortable">
    <div class="box span6">
        <div class="box-header">
            <h2><i class="halflings-icon align-justify"></i><span class="break"></span>Yeni Slider Tablosu</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
            </div>
        </div>
        <div class="row-fluid sortable">
            <div class="box span12">
                <div class="box-header" data-original-title>
                    <h2><i class="halflings-icon edit"></i>
                    <div class="box-icon">
                        <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                        <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                        <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
                    </div>
                </div>
@using (Html.BeginForm("AddSlider", "Slider", FormMethod.Post, new { @class = "form-horizontal" }))
{
               <div class="box-content">
                    <form class="form-horizontal">
                        <fieldset>
                            <div class="control-group">

                             @Html.LabelFor(m => m.SliderText, new { @class="col-sm-3-control-label"})
                                
                              
                                <div class="controls">
                                    @Html.TextBoxFor(m=>m.SliderText, new { @class="form-control",placeholder="Slider Yazısı"})
                                    
                                  
                                </div>
                            </div>
                            <div class="control-group">
                                @Html.LabelFor(m => m.BaslangicTarihi, new { @class = "col-sm-3-control-label" })
                                <div class="controls">
                                    @Html.TextBoxFor(m => m.BaslangicTarihi, new { @class = "form-control", placeholder = "Başlangıç Tarihi" })
                                </div>
                                <div class="control-group">
                                    @Html.LabelFor(m => m.BitisTarih, new { @class = "col-sm-3-control-label" })
                                    <div class="controls">
                                        @Html.TextBoxFor(m => m.BitisTarih, new { @class = "form-control", placeholder = "Bitiş Tarihi" })
                                    </div>
                                </div>
                            <div class="control-group">
                                @Html.LabelFor(m => m.ResimYolu, new { @class = "col-sm-3-control-label" })
                                <div class="controls">
                                    @Html.TextBoxFor(m => m.ResimYolu, new { @class = "form-control", placeholder = "Resim Yolu" })
                                </div>
                            </div>
                            <div class="form-actions">
                                <button type="submit" class="btn btn-primary">Kaydet</button>
                                <button type="reset" class="btn">Vazgeç</button>
                            </div>
                        </fieldset>
                    </form>
                </div>
          

        <!-- start: JavaScript-->
        <script src="~/tema/js/jquery-1.9.1.min.js"></script>
        <script src="~/tema/js/jquery-migrate-1.0.0.min.js"></script>

        <script src="~/tema/js/jquery-ui-1.10.0.custom.min.js"></script>

        <script src="~/tema/js/jquery.ui.touch-punch.js"></script>

        <script src="~/tema/js/modernizr.js"></script>

        <script src="~/tema/js/bootstrap.min.js"></script>

        <script src="~/tema/js/jquery.cookie.js"></script>

        <script src='~/tema/js/fullcalendar.min.js'></script>

        <script src='~/tema/js/jquery.dataTables.min.js'></script>
        <script src="~/tema/js/excanvas.js"></script>
        <script src="~/tema/js/jquery.flot.js"></script>
        <script src="~/tema/js/jquery.flot.pie.js"></script>
        <script src="~/tema/js/jquery.flot.stack.js"></script>
        <script src="~/tema/js/jquery.flot.resize.min.js"></script>

        <script src="~/tema/js/jquery.chosen.min.js"></script>

        <script src="~/tema/js/jquery.uniform.min.js"></script>

        <script src="~/tema/js/jquery.cleditor.min.js"></script>

        <script src="~/tema/js/jquery.noty.js"></script>

        <script src="~/tema/js/jquery.elfinder.min.js"></script>

        <script src="~/tema/js/jquery.raty.min.js"></script>

        <script src="~/tema/js/jquery.iphone.toggle.js"></script>

        <script src="~/tema/js/jquery.uploadify-3.1.min.js"></script>

        <script src="~/tema/js/jquery.gritter.min.js"></script>

        <script src="~/tema/js/jquery.imagesloaded.js"></script>

        <script src="~/tema/js/jquery.masonry.min.js"></script>

        <script src="~/tema/js/jquery.knob.modified.js"></script>

        <script src="~/tema/js/jquery.sparkline.min.js"></script>

        <script src="~/tema/js/counter.js"></script>

        <script src="~/tema/js/retina.js"></script>
        <script src="~/tema/js/custom.js"></script>
        <!-- end: JavaScript-->
}     

FilmBilgileriSistemi/Areas/Admin/Views/Slider/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="row-fluid sortable">
    <div class="box span6">
        <div class="box-header">
            <h2><i class="halflings-icon align-justify"></i><span class="break"></span>Slider Tablosu</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Başlangıç Tarihi</th>
                        <th>Bitiş Tarihi</th>
                        <th>Text</th>
                        <th>Resim Yolu</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.ID</td>
                            <td> @item.BaslangicTarihi</td>
                            <td >@item.BitisTarih</td>
                            <td >@item.SliderText</td>
                            <td> @item.ResimYolu</td>
                        </tr>
                    }


                </tbody>
            </table>
        </div>
        </div>
            </div>
       
    

   